### ISSUE TITLE
Problem with the AudioRL.tar.xz file

### ISSUE THREAD

**Issue by ChristianBrignone** [petrosgk/AudioRL#1]
Hi, i'm very interested in this project and would like to try it but i think there is a problem with the AudioRL.tar.xz file, it seems to be empty! Could you please check it? Thanks

**Comment by petrosgk** [comment]
Hi, apparently the repository is over its LFS bandwidth quota, so GitHub won't allow AudioRL.tar.xz file to be downloaded. This is what I get when using `git clone https://github.com/petrosgk/AudioRL`:

```
Downloading AudioRL.tar.xz (760 MB)
Error downloading object: AudioRL.tar.xz (9163d53): Smudge error: Error downloading AudioRL.tar.xz (9163d5342a5441dc540f8d6637ed6a4916aeb90c86611e4e2777f00cddaf5069): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

I will try uploading the file somewhere else and have a link in README.md.

**Comment by ChristianBrignone** [comment]
Thanks!

**Comment by petrosgk** [comment]
I've uploaded the project files [here](https://drive.google.com/file/d/1-nZDmFVzcZjacaP1kIO5Tj8gooP_gRvq/view?usp=sharing). I've also updated README.md with the link.
